[profile.default]
solc_version = "0.8.28"
evm_version = "prague"
optimizer_runs = 5_000
src = "contracts/1delta"
out = "out"
libs = ["lib"]

[fmt]
line_length = 150
tab_width = 4
multiline_func_header = "all"

[lint]
exclude_lints = ["mixed-case-variable"]
